# Generated by Django 5.1 on 2024-09-06 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand', 'verbose_name_plural': 'Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Producto'},
        ),
    ]
