# Generated by Django 5.1 on 2024-09-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_brand_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/img/'),
        ),
    ]
